apiVersion: v2
description: Chart Operator ServiceMonitors
name: chart-operator-servicemonitors
version: 1.0.0
appVersion: 1.0.0
annotations:
  application.giantswarm.io/team: "honeybadger"
home: https://github.com/giantswarm/chart-operator-servicemonitors
keywords:
  - monitoring
restrictions:
  clusterSingleton: true
  namespaceSingleton: true
  fixedNamespace: giantswarm
type: application
